name: PR Merge and Tag Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Determine the new version number based on the latest tag and PR title
      - name: Determine version
        id: version
        uses: anothrNick/github-tag-action@v1.61.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          tag_suffix: ''
          title_regex: '^(MAJOR|MINOR|PATCH):(.*)$'
          commit_filter: '.*'

      # Update the tag to the new version number
      - name: Create tag
        id: create_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: ${{ steps.version.outputs.tag }}
          body: 'Automatically generated tag based on PR merge'
          draft: false
          prerelease: false
