name: Bump version
on:
  pull_request:
    types: [closed]
    branches:
      - main
      
      
jobs:
  build:
    permissions: write-all
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version
      id: version
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    
    - name: Create tag
      id: create_tag
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        release_name: ${{ steps.version.outputs.tag }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
